In [1]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np
import os.path
import csv
from sklearn.svm import SVC
from sklearn.svm import NuSVC
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn import grid_search
import sklearn.linear_model as linear_model
import sklearn.metrics as metrics
from sklearn import preprocessing
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, make_scorer
from random import randint
from sklearn import tree
from sklearn.decomposition import PCA
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import math
import time
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

from metrics.Correlation import Correlation
from IO.Write import Write
from IO.Read import Read
from metrics.RSquare import RSquare
from DataSet.Dataset import DataSet


def setIdToName(aList):
    
    ids = {}
    nameToId = {}
    idToName = {}
    count = 0
    
    for i in aList:
        
        nameToId[i] = count
        idToName[count] = i
        count += 1
        
    ids['nameToId'] = nameToId
    ids['idToName'] = idToName
    
    return ids

def createNewIds(oldsnps,snps):
    
    nameToId = {}
    idToName = {}
    newIds = {}
    
    oldIds = oldsnps['snps']['idToName']
    
    for i in range(len(snps)):
        
        nameToId[oldIds[snps[i]]] = i
        idToName[i] = oldIds[snps[i]]
        
    newIds['nameToId'] = nameToId
    newIds['idToName'] = idToName
        
    return newIds

def setSnpsCode(patients,chromosomes):
    
    for i in patients.keys():
        patients[i].snpCode(chromosomes)
        
    return patients
    

def tables(sampleX,sampleY,k):
  
    samples = {}
    
    for run in range(1,k+1):
        
        d1 = {}
        

        dataTestX = sampleX[run]
        dataTestY = sampleY[run]

        n = 0

        for i in sampleX.keys():

            if i != run:

                n += len(sampleX[i])

        dataTrainX = np.zeros((n,len(sampleX[1].T)),dtype = int)
        dataTrainY = np.zeros((n,),dtype = int)

        count = 0

        for sample in sampleX.keys():

            if sample != run:

                 for i in range(len(sampleX[sample])):
                    for j in range(len(sampleX[sample].T)):
                        dataTrainX[count,j] = sampleX[sample][i,j]

                    dataTrainY[count] = sampleY[sample][i]
                    count += 1

        d1['trainX'] = dataTrainX
        d1['trainY'] = dataTrainY
        d1['testX'] = dataTestX
        d1['testY'] = dataTestY
        
        samples[run] = d1
    
    return samples
    
def kSampleData(k,X,Y):
    
    x = int (len(X) / k)
    allElements = np.zeros((len(X),),dtype = int)
    
    count1 = 1
    sampleX = {}
    sampleY = {}
   
    
    while count1 <= k:
        count2 = 1
        sampleData = []
        
        if count1 == k:
            x =  len(X) - ((k-1) * x)
        
        dataX = np.zeros((x,len(X.T)),dtype = int)
        dataY = np.zeros((x,),dtype = int)
        
        while count2 <= x:
            
            aRand = randint(0,len(X)-1)
            
            while allElements[aRand] == 1:
                
                aRand = randint(0,len(X)-1)
            
            allElements[aRand] = 1
            sampleData.append(aRand)
            count2 += 1
            
        for i in range(len(sampleData)):
            for j in range(len(X.T)):
                dataX[i,j] = X[sampleData[i],j]
            
            dataY[i] = Y[sampleData[i]]
            
        sampleX[count1] = dataX
        sampleY[count1] = dataY
        count1 +=1
        
    return tables(sampleX,sampleY,k)




def createNewTable(snps,X):
    
    newX = np.zeros((len(X),len(snps)),dtype = int)
    count=0
    
    
    
    for i in range(len(newX)):
        for j in range(len(newX.T)):
            newX[i,j] = -1
    
    for i in range(len(snps)):
        
        newX[:,i] = X[:,snps[i]]
        
        
    print("new shape = ",newX.shape)
            
    return newX 



def featuresIds(oldSnps,snps):
    
    features = {}
    
    for i in range(len(snps)):
        features[i] = snps[i]
        
    return features



def crossValidiation(X, Y, k = 1, continious = True, classifier = None,OLS = False,Logistic = False):
    
    if not classifier:
        print("wrong!!!!!!! you have to choise a classifier")
        return
    
    results = {}
    accuracy = {}
    auc = {}
    recall = {}
    precision = {}
    f1Score = {}
    
    sumResults = 0.0
    sumAccuracy = 0.0
    sumAuc = 0.0
    sumRecall = 0.0
    sumPrecision = 0.0
    sumF1Score = 0.0
    
    samples = kSampleData(k,X,Y)
    
    for run in range(1, k + 1):
        
        trainX = samples[run]['trainX']
        trainY = samples[run]['trainY']
        
        #trainX,trainY = balancedData(trainX,trainY)
        
        testX = samples[run]['testX']
        testY = samples[run]['testY']
        
        
        if OLS:
            classifier = sm.OLS(trainY,trainX)
            yPredict = classifier.fit().predict(testX)
        else:

            classifier.fit(trainX, trainY)
            yPredict = classifier.predict(testX)
        
        if continious:
            
            for i in range(len(yPredict)):
                
                if (abs(0 - yPredict[i]) - abs(1 - yPredict[i])) <= 1e-10 :
                    yPredict[i] = 0
                else:
                    yPredict[i] = 1
                    
        if Logistic:
            
            probabilities = classifier.predict_proba(testX)
            
            for i in range(len(probabilities)):
                if probabilities[i][1] >= 0.8:
                    yPredict[i] = 1
                else:
                    yPredict[i] = 0
          
        accuracy[run] = metrics.accuracy_score(testY,yPredict)#(yPredict,testY)#
        fpr, tpr, thresholds = metrics.roc_curve(testY,yPredict)
        auc[run] = metrics.auc(fpr,tpr)
        recall[run] = metrics.recall_score(testY,yPredict)
        precision[run] = metrics.precision_score(testY,yPredict)
        f1Score[run] = f1_score(testY, yPredict, average='binary')
        
    
    for i in accuracy.keys():
        sumAccuracy = sumAccuracy + accuracy[i]
        sumAuc = sumAuc + auc[i]
        sumRecall = sumRecall + recall[i]
        sumPrecision = sumPrecision + precision[i]
        sumF1Score = sumF1Score + f1Score[i]
    
    results['accuracy'] = sumAccuracy / k
    results['auc'] = sumAuc / k
    results['recall'] = sumRecall / k
    results['precision'] = sumPrecision / k
    results['f1'] = sumF1Score / k
    
    return results

def writeResultConf(path,name,results):
    
    timee = time.strftime("%d-%m-%Y")
    
    folder = path + name + 'Confu' + " ( " + timee + " ) " + '_'
    #file = path + name + 'Confu' + '.txt'
    
    i=1
    while os.path.exists(folder):
        timee = time.strftime("%d-%m-%Y")
        folder = path + name + 'Confu' + " ( " + timee + " ) " + '_' + str(i) + '_'
    
        i += 1
        
 #   os.makedirs(folder)
    
    file = folder + name + 'Confu' + '.txt' 
    
    write = open(file,'w')
    
    write.write(timee + '\n'+ '\n')
    write.write(name + '\n')
    
    for i in results:
        
        results1 = results[i]
        write.write("Category = " + i + '\n')
        
        for j in results1:
            
            write.write(j + " = " + str(results1[j]) + '\n')
            
        write.write('\n')
        write.write('\n')
        
    write.close()

    

def writeResult(path,name,results,category):
    
    timee = time.strftime("%d-%m-%Y")
    
    folder = path + name  + " ( " + timee + " ) " + '_'
    #file = path + name  + '.txt'
    
    i=1
    while os.path.exists(folder):
        timee = time.strftime("%d-%m-%Y")
        folder = path + name + " ( " + timee + " ) " + '_' + str(i) + '_'
       
        i += 1
        
   # os.makedirs(folder)
    
    file = folder + name + '.txt'
    
    write = open(file,'w')
    
    write.write(timee + '\n'+ '\n')
    write.write(name + '\n')
    write.write("Category = " + category + '\n')
    for i in results[category]:
        
        #results1 = results[i]
        
        
        #for j in results:
            
        write.write(i + " = " + str(results[category][i]) + '\n')
            
        
        
    write.close()

def balancedData(X,Y):
    
    cases = 0
    for i in range(len(Y)):
        if Y[i] == 1:
            cases += 1
            
    Xbalanced = np.zeros((2*cases,len(X.T)))
    Ybalanced = np.zeros(2*cases)
    controls = 0
    count = 0
    selected = np.zeros(len(X))
    '''for i in range(len(Y)):
        if(Y[i] == 0 and controls < cases):
            Xbalanced[count,:] = X[i,:]
            Ybalanced[count] = Y[i]
            controls +=1
            count += 1
        elif Y[i] == 1:
            Xbalanced[count,:] = X[i,:]
            Ybalanced[count] = Y[i]
            count += 1'''
    
    
    for i in range(len(Y)):
        
        if Y[i] == 1:
            Xbalanced[count,:] = X[i,:]
            Ybalanced[count] = Y[i]
            count += 1
            selected[i]=i
    
    while(controls<cases):
        aRand = randint(0,len(X)-1)
        while(selected[aRand] == 1):
            aRand = randint(0,len(X)-1)
            
        Xbalanced[count,:] = X[aRand,:]
        Ybalanced[count] = Y[aRand]
        controls +=1
        count += 1
    
    print("len x = ", Xbalanced.shape)
    print("len y = ", Ybalanced.shape)
    
    return Xbalanced, Ybalanced


def casePatient(X,Y):
    
    cases = 0
    for i in range(len(Y)):
        if Y[i] == 1:
            cases += 1
            
    xCase = np.zeros((cases,len(X.T)))
    count = 0
    for i in range(len(Y)):
        
        if Y[i] == 1:
            xCase[count,:] = X[i,:]
            
            count += 1
            
    
    
    print('cases = ', cases)
    print('xCase shape = ', xCase.shape)
    
    return xCase
            

C:\Users\ANTONIS\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\ANTONIS\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
C:\Users\ANTONIS\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:

path = 'C:\\Users\\ANTONIS\\Desktop\\newSet\\maf\\maf = 0.05\\assoc\\pvalue = 0.001\\'
#path = 'C:\\Users\\ANTONIS\\Desktop\\newSet\\maf\\maf = 0.05\\pvalue = 0.01\\'
#path = 'C:\\Users\\ANTONIS\\Desktop\\newSet\\maf\\maf = 0.05\\pvalue = 0.005\\'
#path = 'C:\\Users\\ANTONIS\\Desktop\\newSet\\maf\\maf = 0.05\\pvalue = 0.05\\'

#path = 'D:\\newSet\\maf\\maf = 0.05\\assoc\\pvalue = 0.001\\'

numberOfChromosomes = 22#'ari8mos twn xromoswmatwn'
patientsTrain = {}
patientsTest = {}
allPatients = {}

chromosomes = {}

read = Read(path,numberOfChromosomes)
write = Write(path,numberOfChromosomes)

patients = read.readPatients('Patients.txt')
chromosomes = read.readSnps(".assoc")
write.writePatientsList(patients,'patient.txt')
write.writeSnpsList(chromosomes)


# run train_lgen bat and test_leg bat

In [3]:

snps = read.getListOfSnps()
ids = {} 


ids['patients'] = setIdToName(list(patients.keys()))
ids['snps'] = setIdToName(snps)


if os.path.exists(path + 'snpCode.txt'):
    print("mphka")
    X, Y = read.readSnpsCode(patients,ids)
    
else:
    
    write.writeSnpLog(read.getNumberOfPatients(),read.getNumberOfSnps(),chromosomes)
    X, Y = read.readSnpsCode(patients,ids)
    
X.shape

mphka
mphka2


(4980, 7799)

# Correlation

In [4]:
#X,Y =balancedData(X,Y)

xTraining, xTest, yTraining1, yTest = train_test_split(X, Y, test_size=0.1, random_state=randint(0,2018))
print("mergex = ",X.shape)
print("xTrain = ",xTraining.shape)
print("xTest = ",xTest.shape)
print("yTrain = ",yTraining1.shape)
print("yTest = ",yTest.shape)

mergex =  (4980, 7799)
xTrain =  (4482, 7799)
xTest =  (498, 7799)
yTrain =  (4482,)
yTest =  (498,)


In [5]:
#xC = casePatient(X,Y)
#cor = Correlation(xC)

cor = Correlation(X)


#cor = RSquare(X)

#cor = Correlation(xTraining)
#cor = RSquare(xTraining)
snpReduc = {}

# Correlation high

In [24]:
down = 40
up = 100 
threshold = 0.7
snpReduc['high'] = cor.getHighCorrelationSnps(threshold, down=down,up=up,c=-2)
write.writeSnpsUsed(snpReduc['high'],ids['snps']['idToName'],chromosomes,'high')

snpsIds =  0
idToName =  7799


# Correlation Low

In [8]:

down = 97
up = 100 
threshold = 0.7
#snpReduc['low'] = cor.getLowCorrelationSnps(threshold, down=down,up=up)
snpReduc['low97'] = cor.getLowCorrelationSnps(threshold, down=down,up=up,c=-2)
write.writeSnpsUsed(snpReduc['low97'],ids['snps']['idToName'],chromosomes,'97%')

snpsIds =  7515
idToName =  7799


In [9]:
down = 100
up = 100 
threshold = 0.7
#snpReduc['low'] = cor.getLowCorrelationSnps(threshold, down=down,up=up)
snpReduc['low100'] = cor.getLowCorrelationSnps(threshold, down=down,up=up,c=-2)
write.writeSnpsUsed(snpReduc['low100'],ids['snps']['idToName'],chromosomes,'100%')

snpsIds =  883
idToName =  7799


In [10]:
print(len(snpReduc['low97']))
print(len(snpReduc['low100']))

7515
883


In [ ]:
'''print(ids['snps']['nameToId']['rs75570604'])
get = cor.getCorrMatrix()

summ = 0 

for i in range(len(get)):
    if get[6555,i] - 0.7 < 1e-10 :
        summ += 1'''

'''for i in range(len(get)):
    sum1 = 0
    for j in range(len(get.T)):
        if get[i,j] - 0.7 < 1e-10 :
            sum1 += 1
    if sum1 == len(get.T)-1:
        summ += 1
'''

'''for i in range(len(get)):
    sum1 = 0
    for j in range(len(get.T)):
        if get[i,j] - 0.7 > 1e-10 :
            sum1 += 1
    if sum1 > summ:
        summ = sum1'''


'''print(summ)
print(len(get))'''

In [11]:
categories = []
#categories = ['low','high']
#categories = ['low']
categories = ['low97','low100']
writeResults2={}
writeResults={}

In [ ]:
'''featuresIdss = {}
featuresIdss['low'] = featuresIds(snpReduc['low'])'''


In [ ]:
'''from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest



test = SelectKBest(score_func=chi2,k = 1000)
fit1 = test.fit(xTraining, yTraining1)
xTraining1 = fit1.transform(xTraining)

fit2 = test.fit(xTest, yTest)
xTest1 = fit2.transform(xTest)

fit3 = test.fit(X, Y)
XX = fit3.transform(X)

print("xtest", xTest1.shape)
print("xtraining", xTraining1.shape)
print("X", XX.shape)'''

# RFR

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import BaggingClassifier

for i in categories:
    r1={}
    writeResults={}
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    clf = RandomForestClassifier()
    #clf.fit(xTraining1, yTraining1)
   
    param_grid = {
              "n_estimators" : [9, 18, 27, 36, 45, 54, 63],
              "min_samples_split": [2, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"],
               "warm_start":[True,False]}
    
    '''param_grid = { 
         'n_estimators':[2000,3000,5000], 
         'max_depth':[5,15,30], 
         'min_samples_split':[2,3], 
        'min_samples_leaf':[1,2],
        "warm_start":[True,False],
                "oob_score":[True,False]}
    '''
    
    # run grid search
    grid_search = GridSearchCV(estimator=clf, param_grid=param_grid,cv = 10,verbose=1)
    
    grid_search.fit(xTraining1, yTraining1)
    
    
    print()
    
    #yPredict4 = clf.predict(xTest1)
    yPredict4 = grid_search.predict(xTest1)

    print(metrics.accuracy_score(yTest,yPredict4))
    print(metrics.confusion_matrix(yTest,yPredict4))
    error4 = mean_squared_error(yTest, yPredict4)
    print("error 4 = ",error4)
    RMSE4 = mean_squared_error(yTest,yPredict4)**0.5
    print("RMSE4 = ",RMSE4)

    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict4)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict4))
    print("precision = ",metrics.precision_score(yTest,yPredict4))
    print("f1Score = ",f1_score(yTest, yPredict4, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict4)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict4)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict4)
    r1['precision'] = metrics.precision_score(yTest,yPredict4)
    r1['f1'] = f1_score(yTest, yPredict4, average='binary')
    writeResults2[i] = r1
    
    print()

    results = crossValidiation(XX, Y, k = 10, classifier = grid_search, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    results['len_snps'] = len(snpReduc[i])
   # results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    
    #writeResult(path,'rfr'+i,writeResults,i)
   # writeResultConf(path,'rfr'+i,writeResults2)
    

In [ ]:
clf.fit(xTraining1, yTraining1)
yPredict4 = clf.predict(xTest1)


print(metrics.accuracy_score(yTest,yPredict4))
print(metrics.confusion_matrix(yTest,yPredict4))
error4 = mean_squared_error(yTest, yPredict4)
print("error 4 = ",error4)
RMSE4 = mean_squared_error(yTest,yPredict4)**0.5
print("RMSE4 = ",RMSE4)

fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict4)
print("AUC = ", metrics.auc(fpr,tpr))
print("recal = ",metrics.recall_score(yTest,yPredict4))
print("precision = ",metrics.precision_score(yTest,yPredict4))
print("f1Score = ",f1_score(yTest, yPredict4, average='binary'))

# SVM KERNEL

In [12]:
from sklearn.svm import NuSVC

for i in categories:
    
    r1 = {}
    r1['down'] = down
    r1['up'] = up
    r1['thres'] = threshold
    writeResults={}
    print("Category = ",i)
    
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    '''  test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)

    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)
    '''
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)

    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    
    
    clf = SVC(kernel='linear')
    #clf = NuSVC(kernel='rbf',nu=0.01)
    clf.fit(xTraining1, yTraining1)
    yPredict2 = clf.predict(xTest1)
    print(metrics.accuracy_score(yTest,yPredict2))
    print(metrics.confusion_matrix(yTest,yPredict2))
    error2 = mean_squared_error(yTest, yPredict2)
    print("error 2 = ",error2)
    RMSE2 = mean_squared_error(yTest,yPredict2)**0.5
    print("RMSE2 = ",RMSE2)
    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict2)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict2))
    print("precision = ",metrics.precision_score(yTest,yPredict2))
    print("f1Score = ",f1_score(yTest, yPredict2, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict2)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict2)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict2)
    r1['precision'] = metrics.precision_score(yTest,yPredict2)
    r1['f1'] = f1_score(yTest, yPredict2, average='binary')
    
    writeResults2[i] = r1
    print()

    results = crossValidiation(XX, Y, k = 10, classifier = clf, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    results['len_snps'] = len(snpReduc[i])
   # results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    writeResult(path,'svm'+i,writeResults,i)
    writeResultConf(path,'svm'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.957831325301
[[386  10]
 [ 11  91]]
error 2 =  0.0421686746988
RMSE2 =  0.205350127097
AUC =  0.933452168746
recal =  0.892156862745
precision =  0.90099009901
f1Score =  0.896551724138

accuracy =  0.938554216867
AUC =  0.895068810682
recal =  0.821409923542
precision =  0.870594811333
f1 =  0.844220997063

Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.931726907631
[[380  16]
 [ 18  84]]
error 2 =  0.0682730923695
RMSE2 =  0.261291202243
AUC =  0.89156268568
recal =  0.823529411765
precision =  0.84
f1Score =  0.831683168317

accuracy =  0.908032128514
AUC =  0.855220935123
recal =  0.765930881724
precision =  0.780709781382
f1 =  0.772883311306



In [13]:
for i in categories:
    
    r1 = {}
    r1['down'] = down
    r1['up'] = up
    r1['thres'] = threshold
    writeResults={}
    print("Category = ",i)
    
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    '''  test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)

    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)
    '''
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)

    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    
    
    clf = SVC()
    #clf = NuSVC(kernel='rbf',nu=0.01)
    clf.fit(xTraining1, yTraining1)
    yPredict2 = clf.predict(xTest1)
    print(metrics.accuracy_score(yTest,yPredict2))
    print(metrics.confusion_matrix(yTest,yPredict2))
    error2 = mean_squared_error(yTest, yPredict2)
    print("error 2 = ",error2)
    RMSE2 = mean_squared_error(yTest,yPredict2)**0.5
    print("RMSE2 = ",RMSE2)
    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict2)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict2))
    print("precision = ",metrics.precision_score(yTest,yPredict2))
    print("f1Score = ",f1_score(yTest, yPredict2, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict2)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict2)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict2)
    r1['precision'] = metrics.precision_score(yTest,yPredict2)
    r1['f1'] = f1_score(yTest, yPredict2, average='binary')
    
    writeResults2[i] = r1
    print()

    results = crossValidiation(XX, Y, k = 10, classifier = clf, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    results['len_snps'] = len(snpReduc[i])
   # results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    writeResult(path,'svmnonlinear'+i,writeResults,i)
    writeResultConf(path,'svmnonlinear'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.809236947791
[[396   0]
 [ 95   7]]
error 2 =  0.190763052209
RMSE2 =  0.436764298231
AUC =  0.53431372549
recal =  0.0686274509804
precision =  1.0
f1Score =  0.128440366972

accuracy =  0.80843373494
AUC =  0.53172318974
recal =  0.0634463794793
precision =  1.0
f1 =  0.118827454727

Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.853413654618
[[396   0]
 [ 73  29]]
error 2 =  0.146586345382
RMSE2 =  0.382865962683
AUC =  0.642156862745
recal =  0.28431372549
precision =  1.0
f1Score =  0.442748091603

accuracy =  0.850803212851
AUC =  0.63692309548
recal =  0.273846190961
precision =  1.0
f1 =  0.427022207713



# LINEAR LOGISTIC REGRESSION 

In [14]:

for i in categories:
    
    r1 = {}
    writeResults={}
    print("Category = ",i)
    
   
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    '''test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)

    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)'''
   
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)
    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    
     

    #lr_clf = linear_model.LogisticRegression()
 
    lr_clf = linear_model.LogisticRegressionCV()
    lr_clf.fit(xTraining1, yTraining1)
    
    yPredict4 = lr_clf.predict(xTest1)

    print(metrics.accuracy_score(yTest,yPredict4))
    print(metrics.confusion_matrix(yTest,yPredict4))
    error4 = mean_squared_error(yTest, yPredict4)
    print("error 4 = ",error4)
    RMSE4 = mean_squared_error(yTest,yPredict4)**0.5
    print("RMSE4 = ",RMSE4)

    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict4)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict4))
    print("precision = ",metrics.precision_score(yTest,yPredict4))
    print("f1Score = ",f1_score(yTest, yPredict4, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict4)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict4)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict4)
    r1['precision'] = metrics.precision_score(yTest,yPredict4)
    r1['f1'] = f1_score(yTest, yPredict4, average='binary')
    writeResults2[i] = r1
    
    print()

    results = crossValidiation(XX, Y, k = 10, classifier = lr_clf, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    results['len_snps'] = len(snpReduc[i])
   # results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    
    writeResult(path,'llrcv'+i,writeResults,i)
    writeResultConf(path,'llrcv'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.957831325301
[[392   4]
 [ 17  85]]
error 4 =  0.0421686746988
RMSE4 =  0.205350127097
AUC =  0.911616161616
recal =  0.833333333333
precision =  0.955056179775
f1Score =  0.890052356021

accuracy =  0.942570281124
AUC =  0.8953020223
recal =  0.815389972627
precision =  0.895422447248
f1 =  0.853226640615

Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.94578313253
[[388   8]
 [ 19  83]]
error 4 =  0.0542168674699
RMSE4 =  0.232845157712
AUC =  0.896761734997
recal =  0.813725490196
precision =  0.912087912088
f1Score =  0.860103626943

accuracy =  0.932530120482
AUC =  0.868528002344
recal =  0.760049968781
precision =  0.895480314828
f1 =  0.821648002003



In [15]:
for iCat in categories:
    
    ids['coef']={}
    XX = createNewTable(snpReduc[iCat],X)

    lr_clf = linear_model.LogisticRegressionCV()
    lr_clf.fit(XX, Y)

    coefs=lr_clf.coef_[0]
    print("before = ",len(set(coefs)))
    ''' for i in range(len(coefs)):
        coefs[i] = abs(coefs[i])'''

    print("after = ",len(set(coefs)))

    idToName = {}
    nameToId = {}

    for i in range(len(coefs)):
        nameToId[coefs[i]] = []

    for i in range(len(coefs)):
        nameToId[coefs[i]].append(i)
        idToName[i] = coefs[i]


    ids['coef']['nameToId'] = nameToId
    ids['coef']['idToName'] = idToName


    sc = sorted(coefs )

    top_30 = []

    for i in sc[-30:]:

        snp = ids['coef']['nameToId'][i][0]
        ids['coef']['nameToId'][i].remove(snp)
        top_30.append(snpReduc[iCat][snp])
     #   top_30.append(snp)

    #snpReduc['low'] = top_30

    write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,iCat+'_not_abs_balanced')
    #write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,'top_30_all_abs')

new shape =  (4980, 7515)
before =  6769
after =  6769
snpsIds =  30
idToName =  7799
new shape =  (4980, 883)
before =  883
after =  883
snpsIds =  30
idToName =  7799


In [16]:
for iCat in categories:
    
    ids['coef']={}
    XX = createNewTable(snpReduc[iCat],X)

    lr_clf = linear_model.LogisticRegressionCV()
    lr_clf.fit(XX, Y)

    coefs=lr_clf.coef_[0]
    print("before = ",len(set(coefs)))
    for i in range(len(coefs)):
        coefs[i] = abs(coefs[i])

    print("after = ",len(set(coefs)))

    idToName = {}
    nameToId = {}

    for i in range(len(coefs)):
        nameToId[coefs[i]] = []

    for i in range(len(coefs)):
        nameToId[coefs[i]].append(i)
        idToName[i] = coefs[i]


    ids['coef']['nameToId'] = nameToId
    ids['coef']['idToName'] = idToName


    sc = sorted(coefs )

    top_30 = []

    for i in sc[-30:]:

        snp = ids['coef']['nameToId'][i][0]
        ids['coef']['nameToId'][i].remove(snp)
        top_30.append(snpReduc[iCat][snp])
     #   top_30.append(snp)

    #snpReduc['low'] = top_30

    write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,iCat+'_abs_balanced')
    #write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,'top_30_all_abs')

new shape =  (4980, 7515)
before =  6769
after =  6769
snpsIds =  30
idToName =  7799
new shape =  (4980, 883)
before =  883
after =  883
snpsIds =  30
idToName =  7799


In [17]:
'''for iCat in categories:
    
    ids['coef']={}
  #  XX = createNewTable(snpReduc[iCat],X)

    lr_clf = linear_model.LogisticRegressionCV()
    lr_clf.fit(X, Y)

    coefs=lr_clf.coef_[0]
    print("before = ",len(set(coefs)))
    for i in range(len(coefs)):
        coefs[i] = abs(coefs[i])

    print("after = ",len(set(coefs)))

    idToName = {}
    nameToId = {}

    for i in range(len(coefs)):
        nameToId[coefs[i]] = []

    for i in range(len(coefs)):
        nameToId[coefs[i]].append(i)
        idToName[i] = coefs[i]


    ids['coef']['nameToId'] = nameToId
    ids['coef']['idToName'] = idToName


    sc = sorted(coefs )

    top_30 = []

    for i in sc[-30:]:

        snp = ids['coef']['nameToId'][i][0]
        ids['coef']['nameToId'][i].remove(snp)
       # top_30.append(snpReduc[iCat][snp])
        top_30.append(snp)

    #snpReduc['low'] = top_30

  #  write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,iCat+'_abs_balanced')
    write.writeSnpsUsed(top_30,ids['snps']['idToName'],chromosomes,'_all_abs')
'''

'for iCat in categories:\n    \n    ids[\'coef\']={}\n  #  XX = createNewTable(snpReduc[iCat],X)\n\n    lr_clf = linear_model.LogisticRegressionCV()\n    lr_clf.fit(X, Y)\n\n    coefs=lr_clf.coef_[0]\n    print("before = ",len(set(coefs)))\n    for i in range(len(coefs)):\n        coefs[i] = abs(coefs[i])\n\n    print("after = ",len(set(coefs)))\n\n    idToName = {}\n    nameToId = {}\n\n    for i in range(len(coefs)):\n        nameToId[coefs[i]] = []\n\n    for i in range(len(coefs)):\n        nameToId[coefs[i]].append(i)\n        idToName[i] = coefs[i]\n\n\n    ids[\'coef\'][\'nameToId\'] = nameToId\n    ids[\'coef\'][\'idToName\'] = idToName\n\n\n    sc = sorted(coefs )\n\n    top_30 = []\n\n    for i in sc[-30:]:\n\n        snp = ids[\'coef\'][\'nameToId\'][i][0]\n        ids[\'coef\'][\'nameToId\'][i].remove(snp)\n       # top_30.append(snpReduc[iCat][snp])\n        top_30.append(snp)\n\n    #snpReduc[\'low\'] = top_30\n\n  #  write.writeSnpsUsed(top_30,ids[\'snps\'][\'idToName\']

In [18]:
from sklearn.naive_bayes import GaussianNB

for i in categories:
    
    r1 = {}
    writeResults={}
    print("Category = ",i)
    
   
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    '''
      test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)

    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)
    
    '''
    
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)
    
    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    

    gnb = GaussianNB()
    gnb.fit(xTraining1, yTraining1)
    yPredict6 = gnb.predict(xTest1)
    print(metrics.accuracy_score(yTest,yPredict6))
    print(metrics.confusion_matrix(yTest,yPredict6))
    error6 = mean_squared_error(yTest, yPredict6)
    print("error 6 = ",error6)
    RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
    print("RMSE6 = ",RMSE6)

    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict6))
    print("precision = ",metrics.precision_score(yTest,yPredict6))
    print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict6)
    r1['precision'] = metrics.precision_score(yTest,yPredict6)
    r1['f1'] = f1_score(yTest, yPredict6, average='binary')
    
    writeResults2[i] = r1
    
    print()

    results = crossValidiation(XX, Y, k = 10,classifier = gnb, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    print()
    results['len_snps'] = len(snpReduc[i])
  #  results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    
    writeResult(path,'gnb'+i,writeResults,i)
    writeResultConf(path,'gnb'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.451807228916
[[135 261]
 [ 12  90]]
error 6 =  0.548192771084
RMSE6 =  0.740400412672
AUC =  0.611631016043
recal =  0.882352941176
precision =  0.25641025641
f1Score =  0.397350993377

accuracy =  0.505823293173
AUC =  0.642777859447
recal =  0.874362913852
precision =  0.27679361389
f1 =  0.420040948537


Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.455823293173
[[133 263]
 [  8  94]]
error 6 =  0.544176706827
RMSE6 =  0.737683337773
AUC =  0.628713606655
recal =  0.921568627451
precision =  0.263305322129
f1Score =  0.409586056645

accuracy =  0.43734939759
AUC =  0.61262128912
recal =  0.908986033872
precision =  0.255123523267
f1 =  0.397409879847




In [19]:
#xTraining.shape
yTraining1.shape

(4482,)

# BERNOULLI


In [20]:

'''xTraining1 = createNewTable(snpReduc['low'],xTraining)
lr_clf = linear_model.LogisticRegressionCV()
lr_clf.fit(xTraining1, yTraining1)

coefs=lr_clf.coef_[0]
top_20 = np.argpartition(coefs, -50)[-50:]
#top_20 = np.argpartition(coefs, 50)[:50]
removedSnps = []
for i in range(len(snpReduc['low'])):
    if i not in top_20:
        removedSnps.append(snpReduc['low'][i])'''



for i in categories:
   
    r1 = {}
    writeResults={}
    print("Category = ",i)
    
   
   
  
    
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    '''
    test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)
    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)

    
    '''
    
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)
    
    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    

    bern = BernoulliNB()
    bern.fit(xTraining1, yTraining1)
    yPredict6 = bern.predict(xTest1)
    print(metrics.accuracy_score(yTest,yPredict6))
    print(metrics.confusion_matrix(yTest,yPredict6))
    error6 = mean_squared_error(yTest, yPredict6)
    print("error 6 = ",error6)
    RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
    print("RMSE6 = ",RMSE6)

    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict6))
    print("precision = ",metrics.precision_score(yTest,yPredict6))
    print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict6)
    r1['precision'] = metrics.precision_score(yTest,yPredict6)
    r1['f1'] = f1_score(yTest, yPredict6, average='binary')
    
    writeResults2[i] = r1
    
    print()

    results = crossValidiation(XX, Y, k = 10,classifier = bern, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    print()
    results['len_snps'] = len(snpReduc[i])
  #  results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    
    writeResult(path,'bernoulli'+i,writeResults,i)
    writeResultConf(path,'bernoulli'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.769076305221
[[305  91]
 [ 24  78]]
error 6 =  0.230923694779
RMSE6 =  0.48054520576
AUC =  0.767453951277
recal =  0.764705882353
precision =  0.461538461538
f1Score =  0.575645756458

accuracy =  0.787751004016
AUC =  0.773184835001
recal =  0.747926321653
precision =  0.488265010107
f1 =  0.589837517265


Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.939759036145
[[379  17]
 [ 13  89]]
error 6 =  0.0602409638554
RMSE6 =  0.245440346837
AUC =  0.914809863339
recal =  0.872549019608
precision =  0.839622641509
f1Score =  0.855769230769

accuracy =  0.934738955823
AUC =  0.898480536383
recal =  0.836908973694
precision =  0.844452892416
f1 =  0.839752578934




In [21]:
'''l= [5,6,7,2,3,4,10,6,7,9,8,5]
top_3 = np.argpartition(l,3)[:3]
print(top_3)
removedSnps=[]
for i in range(len(l)):
    if i not in top_3:
        removedSnps.append(l[i])
print(removedSnps)'''

'l= [5,6,7,2,3,4,10,6,7,9,8,5]\ntop_3 = np.argpartition(l,3)[:3]\nprint(top_3)\nremovedSnps=[]\nfor i in range(len(l)):\n    if i not in top_3:\n        removedSnps.append(l[i])\nprint(removedSnps)'

In [22]:
'''XX = createNewTable(snpReduc['low'],X)
#enc = OneHotEncoder(n_values =3) 
#enc.fit(XX) 
#XX = enc.fit_transform(XX)
#XX = XX.toarray()
print(XX.shape)

re = cross_val_score(bern, XX, Y, cv=10)
print(sum(re)/10)

print()
XX = X
#enc = OneHotEncoder(n_values =3) 
#enc.fit(XX) 
#XX = enc.fit_transform(XX)
#XX = XX.toarray()
print(XX.shape)
re = cross_val_score(bern, XX, Y, cv=10)
print(sum(re)/10)
'''

"XX = createNewTable(snpReduc['low'],X)\n#enc = OneHotEncoder(n_values =3) \n#enc.fit(XX) \n#XX = enc.fit_transform(XX)\n#XX = XX.toarray()\nprint(XX.shape)\n\nre = cross_val_score(bern, XX, Y, cv=10)\nprint(sum(re)/10)\n\nprint()\nXX = X\n#enc = OneHotEncoder(n_values =3) \n#enc.fit(XX) \n#XX = enc.fit_transform(XX)\n#XX = XX.toarray()\nprint(XX.shape)\nre = cross_val_score(bern, XX, Y, cv=10)\nprint(sum(re)/10)\n"

# TREE

In [23]:
from sklearn import tree
from sklearn.ensemble import BaggingClassifier
for i in categories:
    
    r1 = {}
    writeResults={}
    print("Category = ",i)
    
   
    XX = createNewTable(snpReduc[i],X)
    xTraining1 = createNewTable(snpReduc[i],xTraining)
    xTest1 = createNewTable(snpReduc[i],xTest)
    
    
    
    ''' test = SelectKBest(score_func=chi2,k = 500)
    fit1 = test.fit(xTraining1, yTraining1)
    xTraining1 = fit1.transform(xTraining1)

    fit2 = test.fit(xTest1, yTest)
    xTest1 = fit2.transform(xTest1)

    fit3 = test.fit(XX, Y)
    XX = fit3.transform(XX)
    print("xtest", xTest1.shape)
    print("xtraining", xTraining1.shape)
    print("X", XX.shape)
    '''
    
    enc = OneHotEncoder(n_values =3) 
    enc.fit(XX) 
    XX = enc.fit_transform(XX)
    XX = XX.toarray()
    print(XX.shape)

    enc.fit(xTraining1) 
    xTraining1 = enc.fit_transform(xTraining1)
    xTraining1 = xTraining1.toarray()
    print(xTraining1.shape)

    enc.fit(xTest1) 
    xTest1 = enc.fit_transform(xTest1)
    xTest1 = xTest1.toarray()
    print(xTest1.shape)
    
    

    clf= tree.DecisionTreeClassifier()
    
    #clf = BaggingClassifier(clf1, n_estimators=100, max_samples=2,
     #                   random_state=1)
    
    clf.fit(xTraining1, yTraining1)
    yPredict4 = clf.predict(xTest1)

    print(metrics.accuracy_score(yTest,yPredict4))
    print(metrics.confusion_matrix(yTest,yPredict4))
    error4 = mean_squared_error(yTest, yPredict4)
    print("error 4 = ",error4)
    RMSE4 = mean_squared_error(yTest,yPredict4)**0.5
    print("RMSE4 = ",RMSE4)

    fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict4)
    print("AUC = ", metrics.auc(fpr,tpr))
    print("recal = ",metrics.recall_score(yTest,yPredict4))
    print("precision = ",metrics.precision_score(yTest,yPredict4))
    print("f1Score = ",f1_score(yTest, yPredict4, average='binary'))
    
    r1['confu'] = metrics.confusion_matrix(yTest,yPredict4)
    r1['accu'] = metrics.accuracy_score(yTest,yPredict4)
    r1['auc'] = metrics.auc(fpr,tpr)
    r1['recal'] = metrics.recall_score(yTest,yPredict4)
    r1['precision'] = metrics.precision_score(yTest,yPredict4)
    r1['f1'] = f1_score(yTest, yPredict4, average='binary')
    writeResults2[i] = r1
    
    print()

    results = crossValidiation(XX, Y, k = 10, classifier = clf, continious = False)
    results['down'] = down
    results['up'] = up
    results['thres'] = threshold
    print("accuracy = ",results['accuracy'])
    print("AUC = ", results['auc'])
    print("recal = ",results['recall'])
    print("precision = ",results['precision'])
    print("f1 = ",results['f1'])
    results['len_snps'] = len(snpReduc[i])
   # results['len snps'] = 500
    writeResults[i] = results
    
    print()
    
    
    writeResult(path,'tree'+i,writeResults,i)
    writeResultConf(path,'tree'+i,writeResults2)

Category =  low97
new shape =  (4980, 7515)
new shape =  (4482, 7515)
new shape =  (498, 7515)
(4980, 22545)
(4482, 22545)
(498, 22545)
0.68875502008
[[317  79]
 [ 76  26]]
error 4 =  0.31124497992
RMSE4 =  0.557893340989
AUC =  0.527703505645
recal =  0.254901960784
precision =  0.247619047619
f1Score =  0.251207729469

accuracy =  0.69859437751
AUC =  0.535029726735
recal =  0.257977883007
precision =  0.259768567804
f1 =  0.257712301245

Category =  low100
new shape =  (4980, 883)
new shape =  (4482, 883)
new shape =  (498, 883)
(4980, 2649)
(4482, 2649)
(498, 2649)
0.684738955823
[[315  81]
 [ 76  26]]
error 4 =  0.315261044177
RMSE4 =  0.561481116492
AUC =  0.525178253119
recal =  0.254901960784
precision =  0.242990654206
f1Score =  0.248803827751

accuracy =  0.692369477912
AUC =  0.528628721165
recal =  0.251890405107
precision =  0.250674639965
f1 =  0.25092672988



In [ ]:
import graphviz 

for iCat in categories:
    featuresName = []
    for i in range(len(snpReduc[iCat])):
        snp = snpReduc[iCat][i]
        featuresName.append(ids['snps']['idToName'][snp])
    xTraining1 = createNewTable(snpReduc[iCat],xTraining)
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(xTraining1, yTraining1)
    treeee = open(path+iCat+'_balancedTree.dot','w')
    dot_data = tree.export_graphviz(clf, out_file=treeee, 
                            feature_names=featuresName,leaves_parallel =True,max_depth = 6)  
    graph = graphviz.Source(dot_data)


# ALL


In [ ]:

r1 = {}
writeResults2={}
writeResults={}

'''enc = OneHotEncoder(n_values =3) 
enc.fit(X) 
XX = enc.fit_transform(X)
XX = XX.toarray()
print(XX.shape)

enc.fit(xTraining) 
xTraining1 = enc.fit_transform(xTraining)
xTraining1 = xTraining1.toarray()
print(xTraining1.shape)

enc.fit(xTest) 
xTest1 = enc.fit_transform(xTest)
xTest1 = xTest1.toarray()
print(xTest1.shape)'''
    

bern = BernoulliNB()
bern.fit(xTraining, yTraining1)
yPredict6 = bern.predict(xTest)
print(metrics.accuracy_score(yTest,yPredict6))
print(metrics.confusion_matrix(yTest,yPredict6))
error6 = mean_squared_error(yTest, yPredict6)
print("error 6 = ",error6)
RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
print("RMSE6 = ",RMSE6)

fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
print("AUC = ", metrics.auc(fpr,tpr))
print("recal = ",metrics.recall_score(yTest,yPredict6))
print("precision = ",metrics.precision_score(yTest,yPredict6))
print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))

r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
r1['auc'] = metrics.auc(fpr,tpr)
r1['recal'] = metrics.recall_score(yTest,yPredict6)
r1['precision'] = metrics.precision_score(yTest,yPredict6)
r1['f1'] = f1_score(yTest, yPredict6, average='binary')


writeResults2['all'] = r1
    
print()

results = crossValidiation(X, Y, k = 10,classifier = bern, continious = False)
results['down'] = down
results['up'] = up
results['thres'] = threshold    
print("accuracy = ",results['accuracy'])
print("AUC = ", results['auc'])
print("recal = ",results['recall'])
print("precision = ",results['precision'])
print("f1 = ",results['f1'])


results['len_snps'] = len(X.T)
writeResults['all'] = results
    
print()
    
    
writeResult(path,'bernoulli_all',writeResults,'all')
#writeResultConf(path,'bernoulli_all',writeResults2)


In [ ]:
r1 = {}
writeResults2={}
writeResults={}

'''enc = OneHotEncoder(n_values =3) 
enc.fit(X) 
XX = enc.fit_transform(X)
XX = XX.toarray()
print(XX.shape)

enc.fit(xTraining) 
xTraining1 = enc.fit_transform(xTraining)
xTraining1 = xTraining1.toarray()
print(xTraining1.shape)

enc.fit(xTest) 
xTest1 = enc.fit_transform(xTest)
xTest1 = xTest1.toarray()
print(xTest1.shape)'''
    

bern = SVC(kernel='linear')
bern.fit(xTraining, yTraining1)
yPredict6 = bern.predict(xTest)
print(metrics.accuracy_score(yTest,yPredict6))
print(metrics.confusion_matrix(yTest,yPredict6))
error6 = mean_squared_error(yTest, yPredict6)
print("error 6 = ",error6)
RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
print("RMSE6 = ",RMSE6)

fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
print("AUC = ", metrics.auc(fpr,tpr))
print("recal = ",metrics.recall_score(yTest,yPredict6))
print("precision = ",metrics.precision_score(yTest,yPredict6))
print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))

r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
r1['auc'] = metrics.auc(fpr,tpr)
r1['recal'] = metrics.recall_score(yTest,yPredict6)
r1['precision'] = metrics.precision_score(yTest,yPredict6)
r1['f1'] = f1_score(yTest, yPredict6, average='binary')
   
writeResults2['all'] = r1
    
print()

results = crossValidiation(X, Y, k = 10,classifier = bern, continious = False)
results['down'] = down
results['up'] = up
results['thres'] = threshold  
print("accuracy = ",results['accuracy'])
print("AUC = ", results['auc'])
print("recal = ",results['recall'])
print("precision = ",results['precision'])
print("f1 = ",results['f1'])


results['len_snps'] = len(X.T)
writeResults['all'] = results
    
print()
    
    
writeResult(path,'svm_all',writeResults,'all')
#writeResultConf(path,'svm_all',writeResults2)

In [ ]:
r1 = {}
writeResults2={}
writeResults={}

'''enc = OneHotEncoder(n_values =3) 
enc.fit(X) 
XX = enc.fit_transform(X)
XX = XX.toarray()
print(XX.shape)

enc.fit(xTraining) 
xTraining1 = enc.fit_transform(xTraining)
xTraining1 = xTraining1.toarray()
print(xTraining1.shape)

enc.fit(xTest) 
xTest1 = enc.fit_transform(xTest)
xTest1 = xTest1.toarray()
print(xTest1.shape)'''
    

bern = linear_model.LogisticRegressionCV()
bern.fit(xTraining, yTraining1)
yPredict6 = bern.predict(xTest)
print(metrics.accuracy_score(yTest,yPredict6))
print(metrics.confusion_matrix(yTest,yPredict6))
error6 = mean_squared_error(yTest, yPredict6)
print("error 6 = ",error6)
RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
print("RMSE6 = ",RMSE6)

fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
print("AUC = ", metrics.auc(fpr,tpr))
print("recal = ",metrics.recall_score(yTest,yPredict6))
print("precision = ",metrics.precision_score(yTest,yPredict6))
print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))

r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
r1['auc'] = metrics.auc(fpr,tpr)
r1['recal'] = metrics.recall_score(yTest,yPredict6)
r1['precision'] = metrics.precision_score(yTest,yPredict6)
r1['f1'] = f1_score(yTest, yPredict6, average='binary')
   
#writeResults2['all'] = r1

print()

results = crossValidiation(X, Y, k = 10,classifier = bern, continious = False)
results['down'] = down
results['up'] = up
results['thres'] = threshold    
print("accuracy = ",results['accuracy'])
print("AUC = ", results['auc'])
print("recal = ",results['recall'])
print("precision = ",results['precision'])
print("f1 = ",results['f1'])


results['len_snps'] = len(X.T)
writeResults['all'] = results
    
print()
    
    
writeResult(path,'llr_all_CV',writeResults,'all')
#writeResultConf(path,'llr_all_CV',writeResults2)

In [ ]:
r1 = {}
writeResults2={}
writeResults={}

#enc = OneHotEncoder(n_values =3) 
#enc.fit(X) 
#XX = enc.fit_transform(X)
#XX = XX.toarray()
#print(XX.shape)

#enc.fit(xTraining) 
#xTraining1 = enc.fit_transform(xTraining)
#xTraining1 = xTraining1.toarray()
#print(xTraining1.shape)

#enc.fit(xTest) 
#xTest1 = enc.fit_transform(xTest)
#xTest1 = xTest1.toarray()
#print(xTest1.shape)
    

bern = tree.DecisionTreeClassifier()
bern.fit(xTraining, yTraining1)
yPredict6 = bern.predict(xTest)
print(metrics.accuracy_score(yTest,yPredict6))
print(metrics.confusion_matrix(yTest,yPredict6))
error6 = mean_squared_error(yTest, yPredict6)
print("error 6 = ",error6)
RMSE6 = mean_squared_error(yTest,yPredict6)**0.5
print("RMSE6 = ",RMSE6)

fpr, tpr, thresholds = metrics.roc_curve(yTest,yPredict6)
print("AUC = ", metrics.auc(fpr,tpr))
print("recal = ",metrics.recall_score(yTest,yPredict6))
print("precision = ",metrics.precision_score(yTest,yPredict6))
print("f1Score = ",f1_score(yTest, yPredict6, average='binary'))

r1['confu'] = metrics.confusion_matrix(yTest,yPredict6)
r1['accu'] = metrics.accuracy_score(yTest,yPredict6)
r1['auc'] = metrics.auc(fpr,tpr)
r1['recal'] = metrics.recall_score(yTest,yPredict6)
r1['precision'] = metrics.precision_score(yTest,yPredict6)
r1['f1'] = f1_score(yTest, yPredict6, average='binary')
   
writeResults2['all'] = r1

print()

results = crossValidiation(X, Y, k = 10,classifier = bern, continious = False)
results['down'] = down
results['up'] = up
results['thres'] = threshold    
print("accuracy = ",results['accuracy'])
print("AUC = ", results['auc'])
print("recal = ",results['recall'])
print("precision = ",results['precision'])
print("f1 = ",results['f1'])


results['len_snps'] = len(X.T)
writeResults['all'] = results
    
print()
    
    
writeResult(path,'tree_all',writeResults,'all')
#writeResultConf(path,'tree_all',writeResults2)

In [ ]:
featuresName = []
for i in range(len(ids['snps']['idToName'])):
   # snp = ids['snps']['idToName'][i]
    featuresName.append(ids['snps']['idToName'][i])
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, Y)
treeee = open(path+'all_balancedTree.dot','w')
dot_data = tree.export_graphviz(clf, out_file=treeee, 
                            feature_names=featuresName,leaves_parallel =True,max_depth = 6)  
graph = graphviz.Source(dot_data)

In [ ]:
r1={}
writeResults={}

    
    
    
clf = RandomForestClassifier()
#clf.fit(xTraining1, yTraining1)
   
param_grid = {
              "n_estimators" : [9, 18, 27, 36, 45, 54, 63],
              "min_samples_split": [2, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"],
               "warm_start":[True,False]}
    
'''param_grid = { 
         'n_estimators':[2000,3000,5000], 
         'max_depth':[5,15,30], 
         'min_samples_split':[2,3], 
        'min_samples_leaf':[1,2],
        "warm_start":[True,False],
                "oob_score":[True,False]}
'''
    
    # run grid search
grid_search = GridSearchCV(estimator=clf, param_grid=param_grid,cv = 10,verbose=1)
    


results = crossValidiation(X, Y, k = 10, classifier = grid_search, continious = False)
results['down'] = down
results['up'] = up
results['thres'] = threshold
print("accuracy = ",results['accuracy'])
print("AUC = ", results['auc'])
print("recal = ",results['recall'])
print("precision = ",results['precision'])
print("f1 = ",results['f1'])
results['len_snps'] = len(X.T)
   # results['len snps'] = 500
writeResults['all'] = results
    
print()
    
    
writeResult(path,'rfrall',writeResults,'all')